FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150

NAME_MAX_LENGTH = 200

TITLE_NAME_MAX_LENGTH = 200

USERNAME_MAX_LENGTH = 150
USERNAME_RESTRICTED_SLUG = 'me'

EMAIL_MAX_LENGTH = 250

CSV_PATH = 'static/data'
