FIRST_NAME_MAX_LENGTH = 150
LAST_NAME_MAX_LENGTH = 150

CATEGORY_NAME_MAX_LENGTH = 200
GENRE_NAME_MAX_LENGTH = 200

TITLE_NAME_MAX_LENGTH = 200

USERNAME_RESTRICTED_SLUG = 'me'

CSV_PATH = 'static/data'
