# Generated by Django 5.2.9 on 2026-01-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(verbose_name='текст комментария'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
    ]
