# Generated by Django 5.2.9 on 2026-01-05 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reviews",
            "0002_alter_user_options_alter_title_year_alter_user_role",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.PositiveSmallIntegerField(
                error_messages={"validators": "Оценка от 1 до 10!"},
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="оценка",
            ),
        ),
    ]
