# Generated by Django 5.2.9 on 2026-01-05 19:14

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[reviews.validators.validate_username],
            ),
        ),
    ]
